-- Создать пользователя
CREATE USER mvp WITH PASSWORD 'mvp';

-- Базовые права
GRANT CONNECT ON DATABASE mvp_store TO mvp;
GRANT USAGE ON SCHEMA public TO mvp;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mvp;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mvp;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO mvp;
